name: CI/CD

on: [push]

jobs:
  build:

    permissions:
      pages: write      # to deploy to Pages
      id-token: write
    environment:
      name: ${{github.ref_name}}
      url:  https://maks-tkachyk.github.io/test-github-page/index.html
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
   
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn

    - name: Build
      run: yarn build

    - name: Deploy
      run: |
        git config --global user.name $user_name
        git config --global user.email $user_email
        git remote set-url origin https://${github_token}@github.com/${repository}/${{github.run_id}}
        yarn  deploy
      env:
        user_name: ${{github.actor}}
        user_email: 'trachykmakc@gamil.com'
        github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        repository: ${{ github.repository }}

    - name: Override page_url
      id: change-page-url
      run: echo "new_page_url=${{ steps.deployment.outputs.page_url }}${{github.run_id}}/" >> $GITHUB_OUTPUT  
  

      
      