name: CI/CD

on: [push]

jobs:
  build:
    permissions:
      pages: write     
      id-token: write
    environment:
      name: production_environment
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn

    - name: Build
      run: yarn build

    - name: Deploy
      id: deployment
      uses: actions/deploy-pages@v1
