name: CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: emscripten/emsdk
      
    steps:
    - uses: actions/checkout@v3
    - run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DEMSCRIPTEN=ON
    - run: cmake --build build --config ${{env.BUILD_TYPE}}
    - uses: actions/upload-artifact@master
      with:
        name: page
        path: build
        if-no-files-found: error
    
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
      
    steps:
    - uses: actions/download-artifact@master
      with:
        name: page
        path: .
    - uses: actions/configure-pages@v1
    - uses: actions/upload-pages-artifact@v1
      with:
        path: .
    - id: deployment
      uses: actions/deploy-pages@main
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    permissions:
        pages: write      # to deploy to Pages
        id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn

    # - name: Run the tests
    #   yarn test


    - name: Build
      run: yarn build


    # Add a dependency to the build job

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
      

    # Specify runner + deployment step
   
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
      # with:
      #   github_token: ${{ secrets.GITHUB_TOKEN }}
      #   publish_dir: ./build
      #   commit_message: ${{ github.event.head_commit.message }}
      #   enable_jekyll: false
    # - name: "Deploy"
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./build
    #     commit_message: ${{ github.event.head_commit.message }}
    #     enable_jekyll: false